### ISSUE TITLE
Content of important files

### ISSUE THREAD

**Issue by Seluj78** [dee-me-tree-or-love/pypiserver-476-replica#1]
Hi,

I don't have much time to reproduce the issue on a vagrant file right now, but I will try to do so. In the mean time, here is

the output of `history`
https://termbin.com/mabx

the output of `pip3 freeze`
https://termbin.com/23zd5

the content of my `nginx.conf` file
https://termbin.com/wpmu6

the content of my `pypi.service` file
```
[Unit]
Description=A minimal PyPI server for use with pip/easy_install.
After=network.target

[Service]
Type=simple
# systemd requires absolute path here too.
PIDFile=/var/run/pypiserver.pid

ExecStart=/home/ubuntu/venv/bin/pypi-server run -p 8080 -a update,download,list --log-file /var/log/pypiserver.log -P /etc/nginx/.htpasswd /var/www/pypi
ExecStop=/bin/kill -TERM $MAINPID
ExecReload=/bin/kill -HUP $MAINPID
Restart=always

WorkingDirectory=/var/www/pypi

TimeoutStartSec=3
RestartSec=5

[Install]
WantedBy=multi-user.target
```

Do let me know if other files are missing ! :D

**Comment by Seluj78** [comment]
Edit: This starts with the pip installs because it doesn't include my bashrc history (before I installed `zsh` !)


Here it is anyway

```
sudo apt update
sudo apt upgrade
sudo apt install git vim zsh python3 python3-pip python3-venv ca-certificates curl gnupg lsb-release nginx certbot docker-ce docker-ce-cli containerd.io docker-compose-plugin
sudo apt install git vim zsh python3 python3-pip python3-venv ca-certificates curl gnupg lsb-release nginx certbot
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```

**Comment by dee-me-tree-or-love** [comment]
Hey @Seluj78, thanks a lot for the information! This is very helpful! :) To get a final idea of what's happening on the frontend, could you share a screen recording or output of `wget` or `curl` to `<your pypiserver URL>/simple` or `<you pypiserver URL>/packages`? This would help to get a complete picture :) 

_(You can of course mask the important details of your packages and etc from these responses 👌)_

**Comment by Seluj78** [comment]
Of course!

[![asciicast](https://asciinema.org/a/PMnClgFc4fHPMOmsidKXI4ig5.svg)](https://asciinema.org/a/PMnClgFc4fHPMOmsidKXI4ig5)

**Comment by Seluj78** [comment]
Hiya, any news on this ?

**Comment by dee-me-tree-or-love** [comment]
> Hiya, any news on this ?

Hey @Seluj78! Yeah, sorry I was not able to look into it a bit more, but I've looked at the data your provided and in the recording of `wget` and `curl` calls (https://github.com/dee-me-tree-or-love/pypiserver-476-replica/issues/1#issuecomment-1447770176), I see that the status code is `401` for the respective pages, so I am not sure I understand well what problem do you experience. Really sorry if I am misunderstanding this, I thought that the problem was that, with your configuration, these routes - `/simple` and `/packages` - are freely accessible from the frontend/client regardless of the auth parameters, but your recording shows that they are protected. Could you clarify this for me a bit? 

I'd be very thankful because I could not reproduce such a problem locally either. Please let me know!

**Comment by dee-me-tree-or-love** [comment]
All the other files form you look totally fine to me and I tried to model the `nginx` config and the `pypiserver.service` similar to your setup but keeping them to a minimal: https://github.com/dee-me-tree-or-love/pypiserver-476-replica/blob/main/vagrant-setup/nginx.conf (which is a very basic reverse-proxy and excludes the SSL configurations)  and https://github.com/dee-me-tree-or-love/pypiserver-476-replica/blob/main/vagrant-setup/pypiserver.service
